CheckInterval = 1
CertThreshold = 14
Port = 1313

CertChecks= [
    { name = "adamthiede.com", ports= ["443"] },
    { name="asknora.org", ports = ["443"] }
]

TCPChecks = [
    {name = "192.168.7.1", ports =  [ "80", "443", "22" ]},
    {name = "192.168.7.11", ports = [ "53", "80", "22" ]}
]

PingChecks = [
"192.168.7.1",
"192.168.7.10",
"192.168.7.11"
]
